{{- if index .Values "helm-guestbook" "enabled" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Values.cluster.name }}-helm-guestbook'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: 'kubernetes/addons/helm-guestbook'
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
