{{- if index .Values "kustomize-guestbook.enabled" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Values.cluster.name }}-kustomize-guestbook'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: 'kubernetes/addons/kustomize-guestbook'
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{- end }}
